import map from "../data/anilist-mal-map.json" with { type: "json" };

/**
 * AniList id ↔ MAL id, plus the studio.
 *
 * Every fallback source numbers anime the way MAL does — Shikimori mirrors MAL
 * ids outright — while this database stores AniList ids in `user_anime` and
 * `list_entries`. Without translation a fallback returns titles the user's own
 * library cannot recognise, and it fails silently: favourites stop matching,
 * lists render empty, and nothing errors.
 *
 * The ids rarely agree. One Piece happens to be 21 on both, which makes the
 * problem easy to miss; Frieren is 154587 on AniList and 52991 on MAL.
 *
 * The studio is here because no fallback source carries it: both of Shikimori's
 * list endpoints return a thin record, and its detail endpoint is one call per
 * anime. Without it every degraded card reads "Unknown Studio".
 *
 * Generated by `scripts/build-id-map.mjs` from anime-offline-database and
 * committed, because the source is 59 MB and Render's free tier has 512 MB of
 * RAM. Covers 18,858 of the 20,687 entries carrying an AniList id — 91% — with
 * a studio on 80% of those.
 */
type Entry =
  | [malId: number]
  | [malId: number, studio: string]
  | [malId: number, studio: string | 0, genreMask: number];

const table = map as unknown as Record<string, Entry>;

/**
 * AniList's canonical genres, in the bit order `build-id-map.mjs` wrote.
 *
 * NEVER REORDER — the committed JSON stores bit positions, not names. Appending
 * is safe; moving an entry silently relabels every anime that carries that bit.
 */
const GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Horror",
  "Mahou Shoujo",
  "Mecha",
  "Music",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
] as const;

/**
 * Genres for a degraded card.
 *
 * No fallback source carries these cheaply — Shikimori's list endpoints omit
 * them entirely and its detail endpoint is one call per anime — so without this
 * every card served during an outage rendered an empty genre row. Covers 97% of
 * the table at 3.3 genres each.
 */
export function genresFor(anilistId: number): string[] {
  const mask = table[String(anilistId)]?.[2];
  if (typeof mask !== "number" || mask === 0) return [];

  const genres: string[] = [];
  for (let bit = 0; bit < GENRES.length; bit++) {
    if (mask & (1 << bit)) genres.push(GENRES[bit]);
  }
  return genres;
}

let malToAnilist: Map<number, number> | null = null;

export function malIdFor(anilistId: number): number | null {
  return table[String(anilistId)]?.[0] ?? null;
}

/**
 * anime-offline-database stores studios lowercased and with the legal suffix
 * attached — "pierrot co., ltd.", "studio bind". Cards show this next to the
 * title, so it goes out looking like a name rather than a registry entry.
 *
 * Word-initial capitals rather than the studio's own styling: this cannot know
 * that MAPPA is an acronym and Bones is not, and "Mappa" reads as a name while
 * "mappa" reads as a bug.
 */
const LEGAL_SUFFIX = /[,\s]+(co\.?,?\s*ltd\.?|inc\.?|ltd\.?|k\.k\.|llc)\.?$/i;

export function studioFor(anilistId: number): string | null {
  // `0` is the placeholder an entry uses when it has genres but no studio.
  const raw = table[String(anilistId)]?.[1];
  if (typeof raw !== "string" || !raw) return null;

  return raw
    .replace(LEGAL_SUFFIX, "")
    .trim()
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

export function anilistIdFor(malId: number): number | null {
  // Built on first use: the reverse direction is only needed by fallback code
  // paths, and most requests never touch one.
  if (!malToAnilist) {
    malToAnilist = new Map();
    for (const [anilist, entry] of Object.entries(table)) {
      malToAnilist.set(entry[0], Number(anilist));
    }
  }
  return malToAnilist.get(malId) ?? null;
}

/** How many pairs the table holds, for logging and tests. */
export const ID_MAP_SIZE = Object.keys(table).length;
